### ISSUE TITLE
Tool Element Overlap

### ISSUE THREAD

**Issue by awav** [typst/webapp-issues#237]
### Description

I have encountered a user interface issue within Typst webapp where certain tool elements are overlapping. I'm not quite sure if this is by design or an unforeseen issue. I anticipated that the elements would be displayed separately regardless of sizes of the text and rendering windows.

https://github.com/typst/webapp-issues/assets/24483645/3cce0f40-566f-412a-91c8-d6211dec0186

Browser: Arc

### Browsers

Chrome

### OS

macOS

**Comment by GroophyLifefor** [comment]
I did a couple of small experiments and it's pretty easy to fix
_group_1u6br_1 affects all buttons, so it can be "[role="toolbar"]:nth-child(1)" giving a more specific path, 
```css
[role="toolbar"]:nth-child(1) {
    margin-left: 100px;
}
```
And of course this should be corrected, so a media rule should be added.
```css
@media 800-1020 {
    [role="toolbar"]:nth-child(1) {
        margin-left: 0px;
    }
}
```
