### ISSUE TITLE
Strikethrough on roadmap isn't very readable in firefox

### ISSUE THREAD

**Issue by Enivex** [typst/webapp-issues#419]
### Description

https://typst.app/docs/roadmap/

![image](https://github.com/user-attachments/assets/9056da03-7294-4253-bff7-443b8522b01c)

The line goes at x-height instead of through the middle.

### Browsers

Firefox

### OS

Windows

**Comment by reknih** [comment]
I unfortunately cannot move that line without disabling the browser's native strikethrough altogether. The [CSS Text Decoration Module Level 4](https://drafts.csswg.org/css-text-decor-4/#underline-offset) (Editor's Draft) allows for moving underlines only. Instead, I would have to delete the text decoration altogether and simulate the effect with a stroke, which strikes only the first line if the text has multiple lines: 

```css
s, strike, del {
  text-decoration: none;
  position: relative;
}

s::after, strike::after, del::after {
  content: "";
  position: absolute;
  display: block;

  top: .65em;
  left: 0px;
  right: 0px;
  height: .07em;

  background: black;
}
```

Hence, I think that this is blocked on either a Firefox or HK Grotesk (font) bug.

Similar bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1437268
